version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkinsdata:/var/jenkins_home

volumes:
  jenkinsdata:
    name: jenkinsdata
