#!/bin/bash
#update
sudo yum update –y

#install git
sudo yum install -y git

# get repo
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade -y

#install
sudo amazon-linux-extras install epel java-openjdk11 -y
sudo yum install jenkins -y

# start
sudo systemctl daemon-reload
sudo systemctl start jenkins

# make jenkins auto start
sudo chkconfig jenkins on
