#!/bin/bash

#update
sudo yum -y update
sudo yum install -y git

#install docker
sudo amazon-linux-extras install -y docker

#start docker
sudo service docker start

# add permissions to ec2-user to run docker commands without sudo
sudo usermod -a -G docker ec2-user

# make docker auto start
sudo chkconfig docker on

# intall docker-compose
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

#clone workshop material
git clone https://github.com/idevops-academy/DevOps-Workshop.git
cd /DevOps-Workshop/S2-Understanding_Jenkins

#Run Jenkins Container
docker-compose up -d


#restart the terminal after installation
